<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net472</TargetFramework>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.ValueTuple" Version="4.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="SpeakerExpert.Business\SpeakerExpert.Business.csproj" />
    <ProjectReference Include="SpeakerExpert.Models\SpeakerExpert.Models.csproj" />
  </ItemGroup>



</Project>
